# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: 12
    - nodejs_version: 14
    - nodejs_version: 16

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - cmd: npm t

cache:
  - node_modules

os:
  - Default Azure

# Don't actually build using MSBuild
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"

matrix:
  fast_finish: true
